---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  labels:
    run: dummy-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: dummy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy
          image: tampler/dummy-service:v0.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 16Mi
              cpu: "64m"
            limits:
              memory: 128Mi
              cpu: "128m"
